### ISSUE TITLE
Sort recordings table columns

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#55]
Make columns sortable.

Apply similar code to all tables in admin interface.

**Comment by kdarras** [comment]
Please write the solutions you tried and challenges faced @wangpw0103

**Comment by wangpw0103** [comment]
By convention, table column sorting is a web & js orientied requirement. That's why the tablesorter library is considered and 
 looked into, which can be referred https://github.com/Mottie/tablesorter. But according to the comments https://github.com/ecomontec/ecoSound-web/pull/180#issuecomment-1076935096, it's completely another quetions: sort the entire table. 

Anyway, the lesson and learn of using tablesorter are listed here for reference.
1. the document https://mottie.github.io/tablesorter/docs/
2. sortable on editable column is unavailable in php/twig env
note: if sortList attribute is set, the only included columns are sortable
3. sortable column toggle to decreasing does not work as expected for php/twig
note: the events sortStart, sortBegin and sortEnd can be used to debug but is not useful to customized decreasing toggle.

**Comment by kdarras** [comment]
Excellent implementation, congrats @LiuDilongNJ ! Working in Docker.
